from BaseClasses import ItemClassification
from typing import TypedDict, List, Dict, Set


class ItemDict(TypedDict):
    name: str
    classification: ItemClassification


base_id = 2009000


item_table: List[ItemDict] = [
    # Weapons
    {'name': "Revolver - Piercer", #rev0 (blue)
        'classification': ItemClassification.progression},
    {'name': "Revolver - Marksman", #rev2 (green)
        'classification': ItemClassification.progression},
    {'name': "Revolver - Sharpshooter", #rev1 (red)
        'classification': ItemClassification.progression},
    {'name': "Revolver - Standard",
        'classification': ItemClassification.progression},
    {'name': "Revolver - Alternate", #revalt
        'classification': ItemClassification.progression},

    {'name': "Shotgun - Core Eject", #sho0 (blue)
        'classification': ItemClassification.progression},
    {'name': "Shotgun - Pump Charge", #sho1 (green)
        'classification': ItemClassification.progression},
    {'name': "Shotgun - Sawed-On", #sho2 (red)
        'classification': ItemClassification.progression},
    {'name': "Shotgun - Standard",
        'classification': ItemClassification.progression},
    {'name': "Shotgun - Alternate", #shoalt
        'classification': ItemClassification.progression},

    {'name': "Nailgun - Attractor", #nai0 (blue)
        'classification': ItemClassification.progression},
    {'name': "Nailgun - Overheat", #nai1 (green)
        'classification': ItemClassification.progression},
    {'name': "Nailgun - JumpStart", #nai2 (red)
        'classification': ItemClassification.progression},
    {'name': "Nailgun - Standard",
        'classification': ItemClassification.progression},
    {'name': "Nailgun - Alternate", #naialt
        'classification': ItemClassification.progression},

    {'name': "Railcannon - Electric", #rai0 (blue)
        'classification': ItemClassification.progression},
    {'name': "Railcannon - Screwdriver", #rai1 (green)
        'classification': ItemClassification.progression},
    {'name': "Railcannon - Malicious", #rai2 (red)
        'classification': ItemClassification.progression},

    {'name': "Rocket Launcher - Freezeframe", #rock0 (blue)
        'classification': ItemClassification.progression},
    {'name': "Rocket Launcher - S.R.S. Cannon", #rock1 (green)
        'classification': ItemClassification.progression},
    {'name': "Rocket Launcher - Firestarter", #rock2 (red)
        'classification': ItemClassification.progression},

    {'name': "Secondary Fire - Piercer",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Marksman",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Sharpshooter",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Core Eject",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Pump Charge",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Sawed-On",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Attractor",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Overheat",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - JumpStart",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Freezeframe",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - S.R.S. Cannon",
        'classification': ItemClassification.progression},
    {'name': "Secondary Fire - Firestarter",
        'classification': ItemClassification.progression},

    {'name': "Feedbacker", #arm0
        'classification': ItemClassification.progression},
    {'name': "Knuckleblaster", #arm1
        'classification': ItemClassification.progression},
    {'name': "Whiplash", #arm2
        'classification': ItemClassification.progression},

    # Abilities
    {'name': "Stamina Bar",
        'classification': ItemClassification.progression},
    {'name': "Wall Jump",
        'classification': ItemClassification.progression},
    {'name': "Slide",
        'classification': ItemClassification.progression},
    {'name': "Slam",
        'classification': ItemClassification.progression},

    # Skulls
    {'name': "Blue Skull (0-2)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (0-S)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (0-S)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (1-1)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (1-1)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (1-2)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (1-2)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (1-3)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (1-3)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (1-4)", # 4 of them
        'classification': ItemClassification.filler},
    {'name': "Blue Skull (2-3)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (2-3)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (2-4)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (2-4)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (4-2)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (4-2)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (4-3)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (4-4)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (5-1)", # 3 of them
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (5-2)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (5-2)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (5-3)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (5-3)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (6-1)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (7-1)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (7-1)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (7-2)",
        'classification': ItemClassification.progression},
    {'name': "Red Skull (7-S)",
        'classification': ItemClassification.progression},
    {'name': "Blue Skull (7-S)",
        'classification': ItemClassification.progression},

    # Levels
    {'name': "0-2: THE MEATGRINDER",
        'classification': ItemClassification.progression},
    {'name': "0-3: DOUBLE DOWN",
        'classification': ItemClassification.progression},
    {'name': "0-4: A ONE-MACHINE ARMY",
        'classification': ItemClassification.progression},
    {'name': "0-5: CERBERUS",
        'classification': ItemClassification.progression},
    {'name': "1-1: HEART OF THE SUNRISE",
        'classification': ItemClassification.progression},
    {'name': "1-2: THE BURNING WORLD",
        'classification': ItemClassification.progression},
    {'name': "1-3: HALLS OF SACRED REMAINS",
        'classification': ItemClassification.progression},
    {'name': "1-4: CLAIR DE LUNE",
        'classification': ItemClassification.progression},
    {'name': "2-1: BRIDGEBURNER",
        'classification': ItemClassification.progression},
    {'name': "2-2: DEATH AT 20,000 VOLTS",
        'classification': ItemClassification.progression},
    {'name': "2-3: SHEER HEART ATTACK",
        'classification': ItemClassification.progression},
    {'name': "2-4: COURT OF THE CORPSE KING",
        'classification': ItemClassification.progression},
    {'name': "3-1: BELLY OF THE BEAST",
        'classification': ItemClassification.progression},
    {'name': "3-2: IN THE FLESH",
        'classification': ItemClassification.progression},
    {'name': "4-1: SLAVES TO POWER",
        'classification': ItemClassification.progression},
    {'name': "4-2: GOD DAMN THE SUN",
        'classification': ItemClassification.progression},
    {'name': "4-3: A SHOT IN THE DARK",
        'classification': ItemClassification.progression},
    {'name': "4-4: CLAIR DE SOLEIL",
        'classification': ItemClassification.progression},
    {'name': "5-1: IN THE WAKE OF POSEIDON",
        'classification': ItemClassification.progression},
    {'name': "5-2: WAVES OF THE STARLESS SEA",
        'classification': ItemClassification.progression},
    {'name': "5-3: SHIP OF FOOLS",
        'classification': ItemClassification.progression},
    {'name': "5-4: LEVIATHAN",
        'classification': ItemClassification.progression},
    {'name': "6-1: CRY FOR THE WEEPER",
        'classification': ItemClassification.progression},
    {'name': "6-2: AESTHETICS OF HATE",
        'classification': ItemClassification.progression},
    {'name': "7-1: GARDEN OF FORKING PATHS",
        'classification': ItemClassification.progression},
    {'name': "7-2: LIGHT UP THE NIGHT",
        'classification': ItemClassification.progression},
    {'name': "7-3: NO SOUND, NO MEMORY",
        'classification': ItemClassification.progression},
    {'name': "7-4: ...LIKE ANTENNAS TO HEAVEN",
        'classification': ItemClassification.progression},
    {'name': "P-1: SOUL SURVIVOR",
        'classification': ItemClassification.filler},
    {'name': "P-2: WAIT OF THE WORLD",
        'classification': ItemClassification.filler},

    # Layers
    {'name': "OVERTURE: THE MOUTH OF HELL",
        'classification': ItemClassification.progression},
    {'name': "LAYER 1: LIMBO",
        'classification': ItemClassification.progression},
    {'name': "LAYER 2: LUST",
        'classification': ItemClassification.progression},
    {'name': "LAYER 3: GLUTTONY",
        'classification': ItemClassification.progression},
    {'name': "LAYER 4: GREED",
        'classification': ItemClassification.progression},
    {'name': "LAYER 5: WRATH",
        'classification': ItemClassification.progression},
    {'name': "LAYER 6: HERESY",
        'classification': ItemClassification.progression},
    {'name': "LAYER 7: VIOLENCE",
        'classification': ItemClassification.progression},

    # Points
    {'name': "+10,000P",
        'classification': ItemClassification.filler},

    # Powerups
    {'name': "Overheal",
        'classification': ItemClassification.filler},
    {'name': "Dual Wield",
        'classification': ItemClassification.filler},
    {'name': "Infinite Stamina",
        'classification': ItemClassification.filler},
    {'name': "Air Jump",
        'classification': ItemClassification.filler},
    {'name': "Soap",
        'classification': ItemClassification.filler},

    # Traps
    {'name': "Hard Damage",
        'classification': ItemClassification.trap},
    {'name': "Stamina Limiter",
        'classification': ItemClassification.trap},
    {'name': "Wall Jump Limiter",
        'classification': ItemClassification.trap},
    {'name': "Empty Ammunition",
        'classification': ItemClassification.trap},
    {'name': "Radiant Aura",
        'classification': ItemClassification.trap},

    # Switches
    {'name': "Limbo Switch I",
        'classification': ItemClassification.progression},
    {'name': "Limbo Switch II",
        'classification': ItemClassification.progression},
    {'name': "Limbo Switch III",
        'classification': ItemClassification.progression},
    {'name': "Limbo Switch IV",
        'classification': ItemClassification.progression},
    {'name': "Violence Switch I",
        'classification': ItemClassification.progression},
    {'name': "Violence Switch II",
        'classification': ItemClassification.progression},
    {'name': "Violence Switch III",
        'classification': ItemClassification.progression},

    {'name': "Clash Mode",
        'classification': ItemClassification.filler}
]

group_table: Dict[str, Set[str]] = {
    "rev0": {"Revolver - Piercer"},
    "rev1": {"Revolver - Sharpshooter"},
    "rev2": {"Revolver - Marksman"},
    "revalt": {"Revolver - Alternate"},
    "sho0": {"Shotgun - Core Eject"},
    "sho1": {"Shotgun - Pump Charge"},
    "sho2": {"Shotgun - Sawed-On"},
    "shoalt": {"Shotgun - Alternate"},
    "nai0": {"Nailgun - Attractor"},
    "nai1": {"Nailgun - Overheat"},
    "nai2": {"Nailgun - JumpStart"},
    "naialt": {"Nailgun - Alternate"},
    "rai0": {"Railcannon - Electric"},
    "rai1": {"Railcannon - Screwdriver"},
    "rai2": {"Railcannon - Malicious"},
    "rock0": {"Rocket Launcher - Freezeframe"},
    "rock1": {"Rocket Launcher - S.R.S. Cannon"},
    "rock2": {"Rocket Launcher - Firestarter"},
    "arm0": {"Feedbacker"},
    "arm1": {"Knuckleblaster"},
    "arm2": {"Whiplash"},
    "revolver": {"Revolver - Piercer",
                 "Revolver - Marksman",
                 "Revolver - Sharpshooter"},
    "pistol": {"Revolver - Piercer",
               "Revolver - Marksman",
               "Revolver - Sharpshooter"},
    "shotgun": {"Shotgun - Core Eject",
                "Shotgun - Pump Charge",
                "Shotgun - Sawed-On"},
    "nailgun": {"Nailgun - Attractor",
                "Nailgun - Overheat",
                "Nailgun - JumpStart"},
    "railcannon": {"Railcannon - Electric",
                   "Railcannon - Screwdriver",
                   "Railcannon - Malicious"},
    "railgun": {"Railcannon - Electric",
                "Railcannon - Screwdriver",
                "Railcannon - Malicious"},
    "rocket": {"Rocket Launcher - Freezeframe",
               "Rocket Launcher - S.R.S. Cannon",
               "Rocket Launcher - Firestarter"},
    "rocket launcher": {"Rocket Launcher - Freezeframe",
                        "Rocket Launcher - S.R.S. Cannon",
                        "Rocket Launcher - Firestarter"},
    "rpg": {"Rocket Launcher - Freezeframe",
            "Rocket Launcher - S.R.S. Cannon",
            "Rocket Launcher - Firestarter"},
    "junk": {"+10,000P",
             "Overheal",
             "Dual Wield",
             "Infinite Stamina",
             "Air Jump",
             "Soap",
             "Hard Damage",
             "Stamina Limiter",
             "Wall Jump Limiter",
             "Empty Ammunition",
             "Radiant Aura"},
    "filler": {"+10,000P",
               "Overheal",
               "Dual Wield",
               "Infinite Stamina",
               "Air Jump",
               "Soap"},
    "trap": {"Hard Damage",
             "Stamina Limiter",
             "Wall Jump Limiter",
             "Empty Ammunition",
             "Radiant Aura"},
    "dash": {"Stamina Bar"},
    "walljump": {"Wall Jump"},
    "levels": {"0-2: THE MEATGRINDER",
               "0-3: DOUBLE DOWN",
               "0-4: A ONE-MACHINE ARMY",
               "0-5: CERBERUS",
               "1-1: HEART OF THE SUNRISE",
               "1-2: THE BURNING WORLD",
               "1-3: HALLS OF SACRED REMAINS",
               "1-4: CLAIR DE LUNE",
               "2-1: BRIDGEBURNER",
               "2-2: DEATH AT 20,000 VOLTS",
               "2-3: SHEER HEART ATTACK",
               "2-4: COURT OF THE CORPSE KING",
               "3-1: BELLY OF THE BEAST",
               "3-2: IN THE FLESH",
               "4-1: SLAVES TO POWER",
               "4-2: GOD DAMN THE SUN",
               "4-3: A SHOT IN THE DARK",
               "4-4: CLAIR DE SOLEIL",
               "5-1: IN THE WAKE OF POSEIDON",
               "5-2: WAVES OF THE STARLESS SEA",
               "5-3: SHIP OF FOOLS",
               "5-4: LEVIATHAN",
               "6-1: CRY FOR THE WEEPER",
               "6-2: AESTHETICS OF HATE",
               "7-1: GARDEN OF FORKING PATHS",
               "7-2: LIGHT UP THE NIGHT",
               "7-3: NO SOUND, NO MEMORY",
               "7-4: ...LIKE ANTENNAS TO HEAVEN"},
    "layers": {"OVERTURE: THE MOUTH OF HELL",
               "LAYER 1: LIMBO",
               "LAYER 2: LUST",
               "LAYER 3: GLUTTONY",
               "LAYER 4: GREED",
               "LAYER 5: WRATH",
               "LAYER 6: HERESY",
               "LAYER 7: VIOLENCE"},
    "start_weapons": {"Revolver - Piercer",
                      "Revolver - Marksman",
                      "Revolver - Sharpshooter",
                      "Shotgun - Core Eject",
                      "Shotgun - Pump Charge",
                      "Shotgun - Sawed-On",
                      "Nailgun - Attractor",
                      "Nailgun - Overheat",
                      "Nailgun - JumpStart",
                      "Railcannon - Electric",
                      "Railcannon - Screwdriver",
                      "Railcannon - Malicious",
                      "Rocket Launcher - Freezeframe",
                      "Rocket Launcher - S.R.S. Cannon",
                      "Rocket Launcher - Firestarter",
                      "Feedbacker",
                      "Knuckleblaster"},
    "0-2": {"0-2: THE MEATGRINDER"},
    "0-3": {"0-3: DOUBLE DOWN"},
    "0-4": {"0-4: A ONE-MACHINE ARMY"},
    "0-5": {"0-5: CERBERUS"},
    "1-1": {"1-1: HEART OF THE SUNRISE"},
    "1-2": {"1-2: THE BURNING WORLD"},
    "1-3": {"1-3: HALLS OF SACRED REMAINS"},
    "1-4": {"1-4: CLAIR DE LUNE"},
    "2-1": {"2-1: BRIDGEBURNER"},
    "2-2": {"2-2: DEATH AT 20,000 VOLTS"},
    "2-3": {"2-3: SHEER HEART ATTACK"},
    "2-4": {"2-4: COURT OF THE CORPSE KING"},
    "3-1": {"3-1: BELLY OF THE BEAST"},
    "3-2": {"3-2: IN THE FLESH"},
    "4-1": {"4-1: SLAVES TO POWER"},
    "4-2": {"4-2: GOD DAMN THE SUN"},
    "4-3": {"4-3: A SHOT IN THE DARK"},
    "4-4": {"4-4: CLAIR DE SOLEIL"},
    "5-1": {"5-1: IN THE WAKE OF POSEIDON"},
    "5-2": {"5-2: WAVES OF THE STARLESS SEA"},
    "5-3": {"5-3: SHIP OF FOOLS"},
    "5-4": {"5-4: LEVIATHAN"},
    "6-1": {"6-1: CRY FOR THE WEEPER"},
    "6-2": {"6-2: AESTHETICS OF HATE"},
    "7-1": {"7-1: GARDEN OF FORKING PATHS"},
    "7-2": {"7-2: LIGHT UP THE NIGHT"},
    "7-3": {"7-3: NO SOUND, NO MEMORY"},
    "7-4": {"7-4: ...LIKE ANTENNAS TO HEAVEN"},
    "P-1": {"P-1: SOUL SURVIVOR"},
    "P-2": {"P-2: WAIT OF THE WORLD"},
    "overture": {"OVERTURE: THE MOUTH OF HELL"},
    "prologue": {"OVERTURE: THE MOUTH OF HELL"},
    "prelude": {"OVERTURE: THE MOUTH OF HELL"},
    "layer 1": {"LAYER 1: LIMBO"},
    "limbo": {"LAYER 1: LIMBO"},
    "layer 2": {"LAYER 2: LUST"},
    "lust": {"LAYER 2: LUST"},
    "layer 3": {"LAYER 3: GLUTTONY"},
    "gluttony": {"LAYER 3: GLUTTONY"},
    "layer 4": {"LAYER 4: GREED"},
    "greed": {"LAYER 4: GREED"},
    "layer 5": {"LAYER 5: WRATH"},
    "wrath": {"LAYER 5: WRATH"},
    "layer 6": {"LAYER 6: HERESY"},
    "heresy": {"LAYER 6: HERESY"},
    "layer 7": {"LAYER 7: VIOLENCE"},
    "violence": {"LAYER 7: VIOLENCE"},
}