from typing import Dict, List


multilayer_music: Dict[str, str] = {
    "1": "Into the Fire",
    "2": "Unstoppable Force",
    "3": "Into the Fire",
    "4": "Unstoppable Force",
    "6B": "A Shattered Illusion",
    "7B": "A Complete and Utter Destruction of the Senses",
    "8": "Castle Vein",
    "10": "Cold Winds",
    "11": "Requiem",
    "12": "Panic Betrayer",
    "14A": "Guts",
    "14B": "Glory",
    "16": "Dune Eternal",
    "17": "Sands of Tide",
    "18A": "Dancer in the Darkness (Phase 1)",
    "18B": "Dancer in the Darkness (Phase 2)",
    "18C": "Dancer in the Darkness (Phase 3)",
    "20": "Deep Blue",
    "22A": "Death Odyssey",
    "22B": "Death Odyssey Aftermath",
    "24A": "Altars of Apostasy",
    "26B": "The World Looks Red",
    "27A": "Do Robots Dream of Eternal Sleep?",
    "27B": "Hear! The Siren Song Call of Death",
    "28B": "Danse Macabre",
    "30A": "In Absentia Logos",
    "30B": "Spiral Out (Keep Going)",
    "31A": "Never Odd Or Even",
    "31B": "No Devil Lived On",
    "31D": "No Devil Lived On (Shopping)",
    "32A": "The Break (Crimson Glass deComposition)",
    "32B": "The Shattering Circle, or: A Charade of Shadeless Ones and Zeroes Rearranged ad Nihilum",
    "32C": "Event Horizon (Reach for the Sun and Burn! Burn! Burn!)",
    "100A": "A Heart of Cold",
    "100B": "Dead Heat Pulse (A Heart of Cold)",
    "101": "A Part Falling",
    "667A": "Tenebre Rosso Sangue"
}

singlelayer_music: Dict[str, str] = {
    "5": "Cerberus",
    "6A": "A Thousand Greetings",
    "7A": "A Thousand Greetings (Alternate)",
    "9A": "Clair de Lune",
    "9B": "Versus",
    "13": "In the Presence of a King",
    "15A": "Bach: BWV 639 \"I call to you, Lord Jesus Christ\"",
    "15B": "Divine Intervention",
    "19": "Duel (Versus Reprise)",
    "24B": "Hall of Sacreligious Remains",
    "25A": "Fallen Angel",
    "25B": "The Death of God's Will",
    "26A": "The World Looks White",
    "26C": "Bull of Hell (Phase 1)",
    "26D": "Bull of Hell (Phase 2)",
    "28A": "Suffering Leaves Suffering Leaves",
    "31C": "No Devil Lived On (Ambient)",
    "31E": "Mirror Rim",
    "33": "The Fall",
    "666A": "Chaos",
    "666B": "Order",
    "667B": "Pandemonium",
    "667C": "War"
}

ordered_list: List[str] = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6A",
    "6B",
    "7A",
    "7B",
    "8",
    "9A",
    "9B",
    "10",
    "11",
    "12",
    "13",
    "14A",
    "14B",
    "15A",
    "15B",
    "16",
    "17",
    "18A",
    "18B",
    "18C",
    "19",
    "20",
    "22A",
    "22B",
    "24A",
    "24B",
    "25A",
    "25B",
    "26A",
    "26B",
    "26C",
    "26D",
    "27A",
    "27B",
    "28A",
    "28B",
    "30A",
    "30B",
    "31A",
    "31B",
    "31C",
    "31D",
    "31E",
    "32A",
    "32B",
    "32C",
    "33",
    "100A",
    "100B",
    "101",
    "666A",
    "666B",
    "667A",
    "667B",
    "667C"
]