from typing import Dict, List


multilayer_music: Dict[str, str] = {
    "1": "INTO THE FIRE",
    "2": "UNSTOPPABLE FORCE",
    "3": "INTO THE FIRE",
    "4": "UNSTOPPABLE FORCE",
    "6B": "A SHATTERED ILLUSION",
    "7B": "A COMPLETE AND UTTER DESTRUCTION OF THE SENSES",
    "8": "CASTLE VEIN",
    "10": "COLD WINDS",
    "11": "REQUIEM",
    "12": "PANIC BETRAYER",
    "14A": "GUTS",
    "14B": "GLORY",
    "16": "DUNE ETERNAL",
    "17": "SANDS OF TIDE",
    "18A": "DANCER IN THE DARKNESS (PHASE 1)",
    "18B": "DANCER IN THE DARKNESS (PHASE 2)",
    "18C": "DANCER IN THE DARKNESS (PHASE 3)",
    "20": "DEEP BLUE",
    "22A": "DEATH ODYSSEY",
    "22B": "DEATH ODYSSEY AFTERMATH",
    "24A": "ALTARS OF APOSTASY",
    "26B": "THE WORLD LOOKS RED",
    "27A": "DO ROBOTS DREAM OF ETERNAL SLEEP?",
    "27B": "HEAR! THE SIREN SONG CALL OF DEATH",
    "28B": "DANSE MACABRE",
    "667A": "TENEBRE ROSSO SANGUE"
}

singlelayer_music: Dict[str, str] = {
    "5": "CERBERUS",
    "6A": "A THOUSAND GREETINGS",
    "7A": "A THOUSAND GREETINGS",
    "9A": "CLAIR DE LUNE",
    "9B": "VERSUS",
    "13": "IN THE PRESENCE OF A KING",
    "15A": "BACH: BWV 639 \"I CALL TO YOU, LORD JESUS CHRIST\"",
    "15B": "DIVINE INTERVENTION",
    "18D": "themeofcancer.wav",
    "19": "DUEL (VERSUS REPRISE)",
    "24B": "HALL OF SACRELIGIOUS REMAINS",
    "25A": "FALLEN ANGEL",
    "25B": "THE DEATH OF GOD'S WILL",
    "26A": "THE WORLD LOOKS WHITE",
    "26C": "themeofcancer.wav",
    "26D": "BULL OF HELL (PHASE 1)",
    "26E": "BULL OF HELL (PHASE 2)",
    "28A": "SUFFERING LEAVES SUFFERING LEAVES",
    "666A": "CHAOS",
    "666B": "ORDER",
    "667B": "PANDEMONIUM",
    "667C": "WAR"
}

ordered_list: List[str] = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6A",
    "6B",
    "7A",
    "7B",
    "8",
    "9A",
    "9B",
    "10",
    "11",
    "12",
    "13",
    "14A",
    "14B",
    "15A",
    "15B",
    "16",
    "17",
    "18A",
    "18B",
    "18C",
    "18D",
    "19",
    "20",
    "22A",
    "22B",
    "24A",
    "24B",
    "25A",
    "25B",
    "26A",
    "26B",
    "26C",
    "26D",
    "26E",
    "27A",
    "27B",
    "28A",
    "28B",
    "666A",
    "666B",
    "667A",
    "667B",
    "667C"
]